
functionNames = {'GetTensor', 'ComputeGeneStats',...
    'MapMatrixInd2Tensor', 'ComputeDensity', 'ConstructTrainingTensor', ...
    'NumSigs', 'CosDist2Deg', 'CosDist', 'DataDir', 'StrJoin', ...
    'RandSigs', 'CosDistMulti', 'ReadStrVec', 'InitRand', ...
    'OuterProduct3', 'RandTensor', 'NormSigs', 'ComputeErrRate', ...
    'MapPairs2Tensor', 'RemoveSigsRandom', 'RemoveSigsChosen', ...
    'TensorDenser', 'SplitTensorDenser', 'SplitTensor2D', ...
    'CompleteTensorKNNCell', 'CompleteTensorKNNDrug', 'CompleteTensor', ...
    'CompleteTensorMean', 'CompleteTensorMean2D', 'TensorCV'};

for f = 1:length(functionNames)
    callLine = ['test_' functionNames{f}];
    fprintf('%s...', callLine)
    eval(callLine);
    disp('passed')
end
