kvec = seq(10, 200, 10)
writeToFile = TRUE
nGenes = 40

### Load disease signatures
load(DataDir('expr/diseaseSigs.RData'))
geneIds = dimnames(tensors$meas)[[2]]
dz_sigs = dz_sigs[,match(geneIds, colnames(dz_sigs))]
stopifnot(all(geneIds == colnames(dz_sigs)))

# filter to only consider disease signatures overlapping landmark genes by at least 40 genes
count = apply(dz_sigs, 1, function(x) length(which(x > 0)))
idx = which(count >= nGenes) 
dz_sigs = dz_sigs[idx,]
dz_annot = dz_annot[idx,]
ndz = nrow(dz_sigs)

# load all data generated by repurp_time.R
AUC = list()
for(method in c('mean', 'mean2', 'knn','tensor')){
  AUC[[method]] = matrix(data=NA, nrow=length(kvec), ncol=ndz, dimnames=list(k=as.character(kvec), dz=dz_annot$do_id))
  for(k in kvec){
    load(ResultsDir(sprintf('large/drug_repurp/dz_rocs_k%d_%s.RData',k, method)))
    AUC[[method]][as.character(k),] = aucs
  }
}

### Plot ROC curves for all diseases for K=100, tensor
k=100
method = 'tensor'
load(ResultsDir(sprintf('large/drug_repurp/dz_rocs_k%d_%s.RData', k, method)))
tiff(PlotDir(sprintf('nGenes%d_disease_ROCs_k%d_%s.tiff', nGenes, k, method)))
str = sprintf('Mean AUC %0.2f +/- %0.2f', mean(aucs), sd(aucs))
print(ggplot(dz_rocs, mapping=aes(x=fpr, y=tpr, group=sig_num)) +
  geom_line(alpha=0.5, colour=GetMethodColor(method), size=1) + 
  theme_bw() +
  theme(text = element_text(size=24)) +
  xlab('FPR') + ylab('TPR') +
  geom_abline(slope=1, intercept=0, color='DarkGrey', lty=2) +
  xlim(c(0,1)) + ylim(c(0,1)))
dev.off()

### Plot AUC distribution across K
A = melt(AUC)
names(A) = c('K','dz','value','method')
S = DataSummary(A, varname='value', groupnames=c('K','method'))
S$method = revalue(S$method, c('mean'='1D-Mean', 'mean2'='2D-Mean', 'tensor'='Tensor', 'knn'='DNPP'))
a = subset(S, K==100)
S = subset(S, K %in%  seq(20,200,30))
tiff(PlotDir('AUC_v_k.tiff'), width=540)
p2 = ggplot(S, aes(x=K, y=value, group=method, color=method)) +
  geom_errorbar(aes(ymin=value-sd, ymax=value+sd), size=0.5, position = position_dodge(7)) + #, alpha=0.6
  geom_line(size=1.5) +
  xlab('K') + ylab('AUC') +
  theme_bw() +
  theme(text=element_text(size=24),
        legend.title = element_blank(),
        legend.position = c(0.8,0.15),
        legend.background = element_rect(fill="white",
                                         size=0.5, linetype="solid", 
                                         colour ="black")) +
  scale_color_manual(values=unlist(GetMethodColors(longName=TRUE)))
print(p2)
dev.off()

### Compute p-values comparing AUC differences for each K
p = list()
diff = list()
for (k in as.character(kvec)) {
  data = data.frame(
    mean = AUC$mean[k,], mean2 = AUC$mean2[k,], knn = AUC$knn[k,], tensor =
      AUC$tensor[k,]
  )
  p$mean[[k]] = t.test(data$mean, data$tensor, paired = TRUE)$p.value
  p$mean2[[k]] = t.test(data$mean2, data$tensor, paired = TRUE)$p.value
  p$knn[[k]] = t.test(data$knn, data$tensor, paired = TRUE)$p.value

  diff$mean[[k]] = data$tensor - data$mean
  diff$mean2[[k]] = data$tensor - data$mean2
  diff$knn[[k]] = data$tensor - data$knn
}
